backend:
  name: git-gateway
  branch: main   # Tumhari repo ki main branch

media_folder: "images/uploads"   # Repo ke andar jaha photos save honge
public_folder: "/images/uploads" # Website pe images dikhane ke liye

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }