backend:
  name: git-gateway
  branch: main   # ya 'master' agar tumhare repo me branch ka naam master hai

media_folder: "images/uploads"   # yaha photos save honge
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }