backend:
  name: git-gateway
  branch: main   # agar tumhara GitHub branch "master" hai to yaha master likhna

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "url", label: "URL", widget: "string" }